org: kuleuven
app: spread
service: db-migration

custom:
  stage: prod

provider:
  name: aws
  region: us-east-2
  stage: prod
  deploymentBucket: spread-${self:custom.stage}-serverlessdeploymentbucket
  runtime: java17
  logRetentionInDays: 14

functions:
  migrate:
    handler: com.spread.Handler
    timeout: 30
    memorySize: 2048
    vpc:
      securityGroupIds:
        - {'Fn::ImportValue': '${self:custom.stage}-db-migration-security-group-id'}
      subnetIds:
        - {'Fn::ImportValue': '${self:custom.stage}-private-subnet1-id'}
        - {'Fn::ImportValue': '${self:custom.stage}-private-subnet2-id'}
    environment:
      DB_HOST: ${env:DB_HOST}
      DB_DATABASE: ${env:DB_DATABASE}
      DB_PORT: ${env:DB_PORT}
      DB_USER: ${env:DB_USER}
      DB_PASSWORD: ${env:DB_PASSWORD}

package:
  artifact: target/db-migration.jar
