org: kuleuven
app: spread
service: spread-ui

custom:
  stage: prod

provider:
  name: aws
  region: us-east-2
  stage: prod
  deploymentBucket: spread-${self:custom.stage}-serverlessdeploymentbucket

resources:
  Resources:

     UIWebsiteBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: spreadviz.org
        AccessControl: PublicRead

     UIRedirectBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: www.spreadviz.org
        AccessControl: LogDeliveryWrite
